server:
  port: 8088

spring:
  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 30MB
  datasource:
    username: root
    password: "#MySQL100419544#"
    url: jdbc:mysql://47.94.131.208:3306/booksystem?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: booksystem.pojo

#showSql
logging:
  level:
    com:
      hnucm:
        springboot: debug
