server:
  port: 8088

spring:
  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 30MB
  datasource:
    username: root
    password: "#MySQL100419544#"
    url: jdbc:mysql://47.94.131.208:3306/booksystem?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC&allowMultiQueries=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    #邮箱配置
  mail:
    host: smtp.126.com
    #改成自己的邮箱
    username: jiaowobiancheng@126.com
    #发送短信后它给你的授权码 填写到这里
    password: GAGHIUAUZHBAANII
    port: 465
    ##编码格式
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          ssl:
            enable: true
          socketFactory:
            port: 465
            class: javax.net.ssl.SSLSocketFactory

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: booksystem.pojo

#showSql
logging:
  level:
    com:
      hnucm:
        springboot: debug
